Update CI (and possibly other fixes)
icecube/skywriter pull request #15
Opened 2023-10-23 09:24 UTC by mlincett

2023-10-23 15:13 UTC, ric-evans commented on skywriter/i3_to_json.py
> +    logging_tools.log_argparse_args(args, logger=LOGGER, level="DEBUG")
It could be nice to make the log-level user configurable

2023-10-23 15:17 UTC, ric-evans requested changes

2023-10-23 16:14 UTC, mlincett commented
> This looks good. Just to clarify is the idea that I3Particles from the original p-frame would still be user specified via `--extra`, including those needed in the online filtering? Or are some keys in the original p-frame always saved by default? Maybe a README would be nice to add to explain the behavior.

All the keys required for the realtime processing are copied from the input to the output P-frame.

The coordinates of I3Particles specified in the `--extra` keys are extracted and written in plaintext to the JSON, but there is no warranty that the corresponding data will be in the output I3Frame (as the user could choose a key not among the ones that are routinely copied). This is no different from the current `main` branch behavior, I believe (but of course it can be improved in the future).

I agree this can be clarified in a README.

2023-10-23 19:40 UTC, tianluyuan approved these changes

2023-10-24 09:34 UTC, mlincett commented on skywriter/logging_utils.py
> +logging.basicConfig(
My purpose is configure the logging for `i3_to_json.py` when run as script, so I guess the solution is putting the `logging.basicConfig` before the call to `main()`. If you have a better suggestion please let me know!

2023-10-24 15:46 UTC, ric-evans commented
> > Looking forward, we'll need to define an entry point pattern. I see two equally suitable patterns:
> > ```
> > 1. multiple entry points: each module has an `if-main` block
> >    
> >    * multiple `argparse`s
> > 
> > 2. one entry point: make a `__main__.py`
> >    
> >    * one `argparse`
> > ```
> 
> We don't really have actual multiple modules now, do we?
> 
> I mostly use the `i3_to_json.py` as a script for testing but then I use `i3_to_json` as a function in SkyMist for all practical purposes. So no strong preference in either direction.

You're right, we don't right now. However, if you wanted to go with one entry point, then there'd need to be refactoring that would be easier to do now than later when we add a new script. BUT, it sounds like multiple entry points are fine :smile: we'll just have to use `python -m` so the helper module is available

2023-10-24 15:47 UTC, ric-evans approved these changes

2023-10-24 15:58 UTC, merged